### PR TITLE
Pass the proper parent classloader to the `ebeanModels` sbt task. Fix #32

### LINKED ISSUE #32: `play.db.ebean.ModelsConfigLoader` being loaded in the wrong classloader
The wrong classloader was used to load class `play.db.ebean.ModelsConfigLoader`, leading to a `java.lang.NoClassDefFoundError:  scala/collection/mutable/StringBuilder` when the task `ebeanModels` task was being instantiated. This is a regression between 1.0.0-RC1 and 1.0.0-RC2, and it's caused by https://github.com/playframework/play-ebean/commit/f2ec51c0adaaceeae7a91729ba53dcd130cc2aab#diff-eb7148de75f2c9c1b5821afd677c5044R111

You can reproduce the issue with the following `build.sbt`
```scala
name := "bug"

version := "0.1"

lazy val root = (project in file("."))
  .enablePlugins(PlayJava, SbtEbean)
  // Of course, the classloader issue happens also if you use PlayScala
```

`project/plugins.sbt`

```scala
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.0-RC2")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "1.0.0-RC2")
```

and, `build.properties`

```scala
sbt.version=0.13.8
```

### PR DESCRIPTION
**Pull request by dotta**
@richdougherty @jroper I'd love to add a test, but I'm not sure this is something easy to achieve. Let me know if you have some insight.

### CODE REVIEW

File: sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala [hunk 1]
```diff
@@ -108,7 +107,7 @@ object SbtEbean extends AutoPlugin {
     // code to load the config as it would be loaded in production
     def withClassLoader[T](block: ClassLoader => T): T = {
       val classpath = unmanagedResourceDirectories.value.map(_.toURI.toURL) ++ dependencyClasspath.value.map(_.data.toURI.toURL)
-      val classLoader = new URLClassLoader(classpath.toArray, null)
+      val classLoader = new URLClassLoader(classpath.toArray, this.getClass.getClassLoader)
```
Comment (jsuereth) [inline sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala]: what was  missing in the previous classloader?  Looks like maybe the "dependencyClasspath" may be invalid if adding sbt's own classpath suddenly works....

**Comment by dotta** [comment]
After talking to @jsuereth, this is definitely not how it should be fixed. I'll look at it tomorrow again if none beats me to it.

File: sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala (hunk 1 above)
Comment (dotta) [inline sbt-play-ebean/src/main/scala/play/ebean/sbt/SbtEbean.scala]: The actual fix had nothing to do with classloader's classpath :-) The classpath was good, the problem was that an exception could be thrown during classloading. Here is a pointer to the actual fix https://github.com/playframework/play-ebean/pull/34

Quite instructive ticket. Thanks @jsuereth for your help, really appreciated it!
