### ISSUE TITLE
`play.db.ebean.ModelsConfigLoader` being loaded in the wrong classloader

### ISSUE THREAD

**Issue by dotta** [playframework/play-ebean#32]
The wrong classloader was used to load class `play.db.ebean.ModelsConfigLoader`, leading to a `java.lang.NoClassDefFoundError:  scala/collection/mutable/StringBuilder` when the task `ebeanModels` task was being instantiated. This is a regression between 1.0.0-RC1 and 1.0.0-RC2, and it's caused by https://github.com/playframework/play-ebean/commit/f2ec51c0adaaceeae7a91729ba53dcd130cc2aab#diff-eb7148de75f2c9c1b5821afd677c5044R111

You can reproduce the issue with the following `build.sbt`
```scala
name := "bug"

version := "0.1"

lazy val root = (project in file("."))
  .enablePlugins(PlayJava, SbtEbean)
  // Of course, the classloader issue happens also if you use PlayScala
```

`project/plugins.sbt`

```scala
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.0-RC2")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "1.0.0-RC2")
```

and, `build.properties`

```scala
sbt.version=0.13.8
```

**Comment by dotta** [comment]
Fixed by https://github.com/playframework/play-ebean/pull/34
