### ISSUE TITLE
Update with latest version of Ebean

### ISSUE THREAD

**Issue by JFCote** [playframework/play-ebean#207]
Hi,

I'm using Play Framework latest version (2.8.X) but the version of Ebean ORM used by "play-ebean" is kind of old. Is it possible to bump it to at least "12.2.2) ? There is a serious bug with mySQL that has been fixed in this version: https://github.com/ebean-orm/ebean/pull/1978

I can also help by create a PR if someone is kind enough to tell me how to bump a version. I checked the code quickly but I'm not sure how this plugin work...

Thank you!

**Comment by almothafar** [comment]
You can override dependencies, in build.sbt:

```sbt
val ebeanDependencies: Seq[sbt.ModuleID] =
  Seq(
    "io.ebean" % "ebean" % "12.6.7",
    "io.ebean" % "ebean-agent" % "12.7.1",
    "io.ebean" % "ebean-migration" % "12.4.0"
  )

inThisBuild(
  List(
    scalaVersion := "2.13.4",
    dependencyOverrides := Seq(
      "com.fasterxml.jackson.module" % "jackson-module-scala_2.13" % "2.12.1", // <- you maybe need this 
    ) ++ ebeanDependencies
  )
)

libraryDependencies ++= Seq(
  guice,
  javaJdbc,
  javaWs,
  caffeine,
  filters,
  "com.typesafe.play" %% "play-json" % "2.9.2",
  //... etc
) ++ ebeanDependencies

```

This is working for me until now and gave me the option to have the latest without waiting plugin updates

**Comment by PromanSEW** [comment]
Migrations don't work with Ebean 12.7.1:
`NoClassDefFoundError: io/ebeaninternal/dbmigration/model/CurrentModel`
Which imported in `EbeanDynamicEvolutions` class

**Comment by mkurz** [comment]
Latest version is now used in the main branch: #245
