### ISSUE TITLE
sbt-play-ebean 6.2.0 doesn't work with Play Framework 2.8.20 (NoClassDefFoundError)

### ISSUE THREAD

**Issue by dEajL3kA** [playframework/play-ebean#388]
After upgrading `sbt-play-ebean` to version **6.2.0**, the application based on Play Framework  **2.8.20**  does **not** work anymore:

(works fine with `sbt-play-ebean` version **6.0.0**)

```
[error] java.lang.NoClassDefFoundError: sbt/internal/inc/PlainVirtualFileConverter
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:98)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] Caused by: java.lang.ClassNotFoundException: sbt.internal.inc.PlainVirtualFileConverter
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:98)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
```

I think this is a bug, since `sbt-play-ebean` version **6.2.0** is supposed to work with Play Framework  **2.8.18+** 😢

**Comment by mkurz** [comment]
Which sbt version are you using in `project/build.properties`?
I recomment 1.7.2

**Comment by mkurz** [comment]
See https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4

> play-ebean `6.2.0-RC4` requires sbt 1.4 or newer

**Comment by dEajL3kA** [comment]
Thanks for response!

I have tried SBT version **1.4.9**, **1.5.8**, **1.6.2** as well as **1.7.3**. But result is the same.

**Comment by mkurz** [comment]
Use 1.7.2, shut down sbt, remote the `target` folder (also `project/target`) and try again

**Comment by dEajL3kA** [comment]
Okay, as soon as I change SBT to version **1.5.x** or any newer (including version **1.7.2**) in `project/build.properties` the build will fail with:

```

[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error]         * org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.2.0, 1.1.1, 1.0.6}
[error]             +- com.github.sbt:sbt-native-packager:1.9.16 (sbtVersion=1.0, scalaVersion=2.12) (depends on 2.1.0)
[error]             +- org.scala-lang:scala-compiler:2.12.16              (depends on 1.0.6)
[error]             +- com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.1.1)
[error]             +- com.typesafe.play:twirl-api_2.12:1.5.1             (depends on 1.2.0)
```

**Comment by mkurz** [comment]
Seems like you upgraded sbt-native-packer to 1.9.16 yourself. If you don't really need to do that, I would just remove it because Play 2.8 comes [with 1.5.2 anyway](https://github.com/playframework/playframework/blob/2.8.20/project/plugins.sbt#L7).
However if you really need to upgrade sbt-native-packager, you can instead put
```
ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
```
in your project/plugins.sbt, see https://github.com/playframework/playframework/releases/tag/2.8.19

**Comment by dEajL3kA** [comment]
Thank you!. I have removed `sbt-native-packager` 1.9.16 for now. But build still fails, now with `NoSuchMethodError`:
```
[error] java.lang.NoSuchMethodError: sbt.internal.inc.Relations.classNames(Ljava/io/File;)Lscala/collection/immutable/Set;
[error]         at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$4(PlayEnhancer.scala:80)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error]         at com.typesafe.play.sbt.enhancer.PlayEnhancer$.getClassesForSources$1(PlayEnhancer.scala:76)
[error]         at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$bytecodeEnhance$3(PlayEnhancer.scala:91)
[error]         at com.typesafe.play.sbt.enhancer.PlayEnhancer$.$anonfun$scopedSettings$3(PlayEnhancer.scala:51)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] (common / Compile / manipulateBytecode) java.lang.NoSuchMethodError: sbt.internal.inc.Relations.classNames(Ljava/io
```

**Comment by mkurz** [comment]
Thats a different thing, starting with play-ebean 6.2 "Play enhancer got removed", see https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4

**Comment by dEajL3kA** [comment]
Does it mean I have to remove `sbt-play-enhancer` from `project/plugins.sbt`?

Well, I gave it a try, but doesn't seem to fix the `NoSuchMethodError` problem:
```
[error] java.lang.NoSuchMethodError: sbt.internal.inc.Relations.products(Ljava/io/File;)Lscala/collection/immutable/Set;
[error]         at com.typesafe.sbteclipse.core.EclipsePlugin$.$anonfun$copyManagedClasses$2(EclipsePlugin.scala:117)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at com.typesafe.sbteclipse.core.EclipsePlugin$.$anonfun$copyManagedClasses$1(EclipsePlugin.scala:116)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
```

**Comment by mkurz** [comment]
You need to upgrade sbt-eclipse to v6.0.0: https://github.com/sbt/sbt-eclipse/releases/tag/6.0.0 in your project/plugins.sbt

**Comment by mkurz** [comment]
// For sbt versions >= 1.4.0
addSbtPlugin("com.github.sbt" % "sbt-eclipse" % "6.0.0")

**Comment by dEajL3kA** [comment]
> // For sbt versions >= 1.4.0
> addSbtPlugin("com.github.sbt" % "sbt-eclipse" % "6.0.0")

Okay, thanks! This seems to fix the build.

But now I'm getting all sorts of errors (failed tests) at *runtime*. Probably result of missing `sbt-play-enhancer` ???

**Comment by mkurz** [comment]
Yes, you need to write getters and setter yourself now.

**Comment by dEajL3kA** [comment]
Could you give a simple example, please?

Suppose I have a model class that looks something like this:
```
@Entity
public class Certificate extends AuditedModel {

    @EmbeddedId
    public CertificateId id;

    @Lob
    public byte[] certificate;

    /* ... */
}
```

...do I need to add a getter and setter method for **every** property/field?

And do I need to change all code that uses the model class to use these getter/setter methods instead of direct field access?

Should the fields the be `private`?

**Comment by mkurz** [comment]
I don't know you codebase but usually yes you want to make the fields private and create getters and setters. Your IDE will probably help you with that. 

Alternative:
You can also set up lombok (https://projectlombok.org/) which can generate getters and setters for you. However if you do that yo have to be aware that the lombok generated getters and setters will not be availabe in twirl templates (meaning you can't can get/set on a instance enhanced by lombok) because twirl templates are actually scala code that is not aware of lombok annotions.
You can workaround that by putting your models in a sbt sub-project and make your main project depend on it, this way the models in your sub-project will get compiled to bytecode first, and will then be availble in twirl templates in your main project as well.

**Comment by dEajL3kA** [comment]
Since we've always used the `sbt-play-enhancer`:

If I write explicit getter/setter methods in my model (`@Entity`) classes, do these methods need to do anything specific to fetch the value from DB and/or persists the value in the DB? Or does it come down to:

```
@Entity
public class Certificate {

    @Lob
    private byte[] certificate;

    public void setCertificate(final byte[] value) {
        certificate = value;
    }

    public byte[] getCertificate() {
        return certificate;
    }

   /* ... */
}
```

I will have a look at lombok.

**Comment by dEajL3kA** [comment]
So, we have a model class in our Play Framework application that looks like this:
```java
@Entity
public class Customer {
    @Id
    public Long id;

    public String email;

    /* ... */
}
```

By applying a de-compiler on the final **`.class`** file, from the last "working" version of our application, I have been able to figure out that the Play Enhancer apparently has translated the above source code into this:
```java
public class Customer implements EntityBean {
    @PropertiesEnhancer$GeneratedAccessor
    public String getEmail() {
        return this._ebean_get_email();
    }

    @PropertiesEnhancer$GeneratedAccessor
    public void setEmail(final String newValue) {
        this._ebean_set_email(newValue);
    }

    protected void _ebean_set_email(final String newValue) {
        this._ebean_intercept.preSetter(true, 14, (Object)this._ebean_get_email(), (Object)newValue);
        this.email = newValue;
    }


    protected void _ebean_set_email(final String newValue) {
        this._ebean_intercept.preSetter(true, 14, (Object)this._ebean_get_email(), (Object)newValue);
        this.email = newValue;
    }
}
```

Do I really have to write getter and setter method like the above myself, for every filed, from now on ???

**Comment by PromanSEW** [comment]
> The Ebean documentation (latest version) says that they don't need getter/setter methods

In Play app Play Ebean plugin runs enhancement manually. So "enhancing" now applying only to model classes, instead of all referencing classes to these fields.
In my app for example I use only setters for correct update DB fields, getters are optional, using fields directly works fine.

**Comment by dEajL3kA** [comment]
> > The Ebean documentation (latest version) says that they don't need getter/setter methods
> 
> In Play app Play Ebean plugin runs enhancement manually. So "enhancing" now applying only to model classes, instead of all referencing classes to these fields. In my app for example I use only setters for correct update DB fields, getters are optional, using fields directly works fine.

But the problem is that the Enhancer has been deprecated and is **not** compatible with the newer SBT versions.

Hence, if I want to switch to a newer SBT version, I have to drop the Enhancer from my `plugins.sbt`, which apparently means that I have to write the *getter* and *setter* methods myself. Unfortunately, as has been shown [above](https://github.com/playframework/play-ebean/issues/388#issuecomment-1680601725), the *getter* and *setter* methods that (until now) had been generated by the Enhancer are actually quite complex.

**Comment by PromanSEW** [comment]
Play runs Ebean agent manually:
https://github.com/playframework/play-ebean/blob/89571c425016c95c61db75e49a5b6f44119588e9/sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala#L67

You should create setters for your models, and Play Ebean plugin will enhance your setters correctly:
```java
public class Foo extends Model {
	public int count;

	public int addCount(int count) {
		return this.count += count;
	}
}
```
After enhancing:
```java
public class Foo extends Model implements EntityBean {
    public int count;

    public int addCount(int count) {
        int var10002 = this._ebean_get_count() + count;
        this._ebean_set_count(var10002);
        return var10002;
    }
}
```
If you used `setCount` as setter, enhancing will convert `this.count = count` to `this._ebean_set_count(count)`, as well, and will not create own setters anymore.
Enhancing runs on compilation of project automatically as SBT task, or on recompilation in dev mode as well, and correctly builds jar with enhanced classes on `dist`.
You can see enhanced classes in `target\scala-2.13\classes\models` at any time, if needed, to see what is under the hood.

**Comment by dEajL3kA** [comment]
Are you saying that [this](https://github.com/playframework/play-ebean/issues/388#issuecomment-1680696170) is supposed to work, even when the Play Enhancer was removed from the `plugins.sbt`?

If so, then it means "enhancing" pretty much still works?

But I'm still a bit confused what _exactly_ I need to change in my existing code, in order to retain the "old" behavior?

**Comment by PromanSEW** [comment]
@dEajL3kA you should convert all you model fields assignments to setter calls at least.
For example `someModel.field = 100` to `model.setField(100)`.
Creating getters is not needed. Getting field values works without them.

**Comment by dEajL3kA** [comment]
This is a rather big project and finding all places will be difficult.

If I add *getter* and *setter* methods, can I make the field itself `private`, so that I can easily find all places that still attempt direct field access?

**Comment by PromanSEW** [comment]
@dEajL3kA yes of course
